### ISSUE TITLE
Infinite Post Job Cleanup w/ Postgres

### ISSUE THREAD

**Issue by vinchg** [hoverkraft-tech/compose-action#117]
**Description:** My docker compose contains postgres, and during post job cleanup, outputs a ridiculous amount of logs and never ends. The documentation seems to describe this behavior as having enabled debug mode, but there is literally no reference on how/when this is done. Any advice would be appreciated. I also wouldn't mind having the option to just not call docker compose down at all.

**Action version:** 2.0.2 / 2.1.0

**Platform:**

- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Repro steps:**  
```
    - name: Docker compose up
      if: steps.check-compose.outputs.exists == 'true'
      uses: hoverkraft-tech/compose-action@v2.1.0
      with:
        compose-file: docker-compose.yaml"
        up-flags: "--quiet-pull"
        down-flags: "--timeout 5"
```
And a docker compose with postgres.
