### ISSUE TITLE
Wait for service to be running/healthy

### ISSUE THREAD

**Issue by jgraichen** [hoverkraft-tech/compose-action#139]
**Is your feature request related to a problem? Please describe.**

Only running `docker compose up -d` starts the services but can continue with the next CI steps before everything is actually running/ready.

For example, the next step setting up the database might fail because PostgreSQL hasn't been finished booting yet.

**Describe the solution you'd like**

I'd like to have an option (or default) to run `docker compose up --wait`:

<blockquote>
<dl>
<dt>--wait
<dd>Wait for services to be running|healthy. Implies detached mode.
<dt>--wait-timeout int
<dd>Maximum duration in seconds to wait for the project to be running|healthy
</dl>
</blockquote>

**Describe alternatives you've considered**

Adding an empty service container only do `depend_on` the things that need to be running. This might work since that container cannot be started before everything is healthy, but means running more containers, having more logs, needing more resources and ugly extra configuration.

**Comment by jgraichen** [comment]
🤦  Of course, I can just add them as `up-flags`:

```yaml
    - uses: hoverkraft-tech/compose-action@v2
      with:
        compose-file: ./docker-compose.yml
        up-flags: --wait --wait-timeout 300
```

Sorry for the noise.

It may still be an interesting candidate as a default flag.
