### ISSUE TITLE
`services-log-level` is not a valid input

### ISSUE THREAD

**Issue by jared-bloomer** [hoverkraft-tech/compose-action#160]
**Description:** 
Using the main branch of the action, the input `services-log-level` is not a valid input, but it does output details when the action uses it. 

When using main branch at the top of the action I see 
```
Warning: Unexpected input(s) 'services-log-level', valid inputs are ['docker-flags', 'compose-file', 'services', 'up-flags', 'down-flags', 'compose-flags', 'cwd', 'compose-version', 'github-token']
```

This was introduced on [PR# 159](https://github.com/hoverkraft-tech/compose-action/pull/159)

**Action version:** 
hoverkraft-tech/compose-action@main

**Platform:**

- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**

- [ ] Hosted
- [x] Self-hosted

**Tools version:**

N/A

**Repro steps:**  
Use the action with the `services-log-level` parameter. Example usage

```
- name: Start Wiremock and UI Services
   uses: hoverkraft-tech/compose-action@main 
   with:
       compose-file: ./subdirectory/docker-compose.yml
       services-log-level: "info"
       services: |
           wiremock
           ui
    env:
       ARTIFACTORY_USER: ${{ secrets.MY_ARTIFACTORY_USER }}
       ARTIFACTORY_TOKEN: ${{ secrets.MY_ARTIFACTORY_TOKEN }}
```

**Expected behavior:** 
No Warnings

**Actual behavior:** 

![Image](https://github.com/user-attachments/assets/1ba271e0-f4e1-4065-97c4-901384cf1e2c)
