### ISSUE TITLE
False positive when docker-compose.yml is not found

### ISSUE THREAD

**Issue by adborden** [hoverkraft-tech/compose-action#21]
The action passes successfully even if the compose file is not found. This could result in a typo causing a false positive. The action should fail if the docker-compose.yml file is missing.

```
Run isbang/compose-action@v1.4.1
  
./docker-compose.yml not exists
```

I have a `docker-compose.yaml` (yaml instead of yml) which is detected just fine with docker-compose however is ignored with the action.

This is my workflow file:

```
---
name: commit

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          up-flags: --exit-code-from gentoo
```

### How to reproduce
1. Create a `docker-compose.yaml`
2. Create the workflow file without specifying `compose-file`

### Actual behavior
Job passes successfully

### Expected behavior
Job fails with message explaining the docker-compose file is not found.
