### ISSUE TITLE
How to support secrets with docker buildkit in github actions?

### ISSUE THREAD

**Issue by dazza-codes** [hoverkraft-tech/compose-action#26]
Does this project support BUILDKIT with secret mounts?  The following vanilla github action does not work with secret mounts.

```yaml
name: Docker application

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test the stack
      run: |
        export DOCKER_DEFAULT_PLATFORM=linux/amd64
        export COMPOSE_DOCKER_CLI_BUILD=1
        export DOCKER_BUILDKIT=1
        echo "GH_SECRET=${{ secrets.GITHUB_TOKEN }}" > /tmp/app_build_env
        docker-compose version
        docker-compose -f docker-compose.yml -f docker-compose-test.yml build --progress=plain
        docker-compose -f docker-compose.yml -f docker-compose-test.yml up --exit-code-from django
      env:
        GH_SECRET: ${{ secrets.GIT_API_RO }}

```

The `Dockerfile` uses some secret mounts, e.g.

```dockerfile
COPY requirements.txt /app/
RUN --mount=type=secret,id=app_build_env \
    if [ -f /run/secrets/app_build_env ]; then export $(cat /run/secrets/app_build_env | xargs); fi \
    && python3 -m pip install -r requirements.txt
```

The compose file has secrets as an env-file, e.g.

```yaml

secrets:
  app_build_env:
    file: /tmp/app_build_env

```

The action has an error that could be due to an outdated version of docker on the ubuntu-latest image?  The same
`docker-compose.yml` file works OK with docker-compose version v2.14.0.

```
Run export DOCKER_DEFAULT_PLATFORM=linux/amd64
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
The Compose file './docker-compose.yml' is invalid because:
services.app.build contains unsupported option: 'secrets'
```

Is there a base image with ubuntu-latest that has already bundled and enabled the latest docker-compose version?

Is this the right way to upgrade docker-compose in a github action, using the ubuntu-latest image?  It seems like a waste of time to run this upgrade on every action if there is already an official image available that bundles this already.

```
    # Upgrade to the latest version of docker and docker-compose
    # https://docs.docker.com/engine/install/ubuntu/
    - name: Upgrade docker-compose
      run: |
        apt update
        apt-get remove -y docker docker-engine docker.io containerd runc 2>1 > /dev/null || true
        apt-get install -y ca-certificates curl gnupg
        mkdir -m 0755 -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
        echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
          tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```
