### ISSUE TITLE
how to docker login

### ISSUE THREAD

**Issue by l-rossetti** [hoverkraft-tech/compose-action#32]
I'm running docker-compose action after docker login but I get error:
`Error: compose up failed {"exitCode":18,"err":"time=\"2023-08-01T14:32:39Z\" level=warning msg=\"The \\\"PWD\\\" variable is not set. Defaulting to a blank string.\"\n node_server Pulling \n cr_server_database Pulling \n node_server Error \n cr_server_database Error \nError response from daemon: pull access denied for cr-server-node_server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied\n","out":""}`

The same docker-login works for standard build and push. How can I fix it?

These are the steps I'm running:

```
- name: Login against registry
  uses: docker/login-action@v2
  with:
    registry: ${{ env.REGISTRY }}
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}

- name: Run docker compose
  uses: isbang/compose-action@v1.5.0
  env:
    IMAGE_TAG: ${{ needs.publish.outputs.image_tag }}
  with:
    compose-file: "./docker-compose.yml"
    up-flags: "--no-build"
    down-flags: "--volumes"
```

**Comment by isbang** [comment]
Do you know why `permission` solved the error? It is ok to update README.md, but I hope to make it clear why permission is required.

**Comment by l-rossetti** [comment]
Permissions is required in my case, cause I'm trying to allow docker-compose to pull from registry (by using `permissions.packages: read`) the docker image I just built, since I just built and pushed the image in the preceding job (which I omitted in the code I posted). 
I guess `permissions.contents: read` is not really needed here. By the way the `permissions` keyword is not really required due to `isbang/compose-action` but to the way github works in case you want to interact with things like github-packages. That's why I think it's worth it to mention in the README.

More info here: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

Here the complete workflow with build and push image:
```
name: Build Push and Test

on:
  push:
    paths-ignore:
      - '.github/workflows/clean-containers.yml'
    branches:
      - 'master'
      - 'ft**'
    tags: [ 'v*.*.*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [20.x] # can have multiple parallel build (e.g. [18.x, 20.x])

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm clean-install

      - name: Build
        run: |
          npm run build

      # - name: Test
      #   run: |
      #     npm run test

  publish:
    name: Publish to registry
    needs: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Login against registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        # don't change this is, because it will be referenced in the next step
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          target: production
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

    # define the outputs of this job to be referenced in other jobs
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}

  run-compose-and-test:
    name: Run compose and test
    needs: publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      #   - name: Execute Docker container at "ghcr.io/${{ github.repository }}:${{ needs.publish.outputs.image_tag }}"
      #     run: |
      #       echo "Running"

      # https://github.com/docker/login-action
      - name: Login against registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/marketplace/actions/docker-compose-action
      # https://docs.docker.com/engine/reference/commandline/compose_up/
      # TODO testing ideas (at the moment we are just testing compose works without testing the app):
      #   https://medium.com/swlh/the-ultimate-guide-to-integration-testing-with-docker-compose-and-sql-f288f05032c9
      #   https://dev.to/sahanonp/setup-docker-for-integration-testing-in-github-action-39fn
      - name: Run docker compose
        uses: isbang/compose-action@v1.5.0
        timeout-minutes: 5
        env:
          IMAGE_TAG: ${{ needs.publish.outputs.image_tag }} # required by docker-compose to pull the right image tag
        with:
          compose-file: "./docker-compose.yml"
          # --no-build cause we want to pull the IMAGE_TAG we just built
          up-flags: "--detach --no-build" # --abort-on-container-exit (but in the abort case you have to omit '--detach')
          down-flags: "--volumes"
```


`docker-compose.yaml` example where I make use of IMAGE_TAG variable defined within the workflow:
```
version: "3.8"

services:

  cr_server_database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database_cr_server:/var/lib/mysql
      - ${PWD}/scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin -u${DB_USER} -p${DB_PASS} ping -h 127.0.0.1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  node_server:
    image: ghcr.io/my-image:${IMAGE_TAG:-dev}
    build:
      context: .
      target: development
    environment:
      DB_HOST: cr_server_database
    ports:
      - "3000:3000"
    depends_on:
      cr_server_database:
        condition: service_healthy

volumes:
  database_cr_server:
```
