### ISSUE TITLE
How to cache compose builds

### ISSUE THREAD

**Issue by humb1t** [hoverkraft-tech/compose-action#41]
More a question, than an issue. What is the best way to cache docker compose steps here, because I use multistage Dockerfile images with build stage inside, yet sometimes its results can be cached.

**Comment by hydrandt** [comment]
If this is useful to someone, I had to do this. What an alchemy. The whole process is in the end not much faster, as it seems that Buildx spends a lot of time writing and loading the layers. Maybe I would have to reduce the images size. Anyway:

```
- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v2

- name: Cache Docker layers
  uses: actions/cache@v3
  with:
    path: /tmp/docker-cache
    key: ${{ runner.OS }}-buildx-${{ hashFiles('requirements.txt', 'frontend/package-lock.json', 'docker/django/Dockerfile', 'docker/frontend/Dockerfile') }}

- name: Build containers
  uses: docker/bake-action@v5
  with:
    files: docker-compose.yaml,.github/tests-cache-config.json
    targets: django,frontend
  env:
    DOCKER_BUILD_SUMMARY: false
    
- name: Run docker-compose
  uses: hoverkraft-tech/compose-action@v2.0.1
  with:
    compose-file: "./docker-compose.yaml"
    up-flags: "--build"
```

The last step will have everything CACHED from the previous one (bake-action).

Content of `.github/tests-cache-config.json`:

```
{
  "target": {
    "django": {
      "cache-to": ["type=local,mode=max,dest=/tmp/docker-cache"],
      "cache-from": ["type=local,mode=max,src=/tmp/docker-cache"],
      "output": ["type=docker"]
    },
    "frontend": {
      "cache-to": ["type=local,mode=max,dest=/tmp/docker-cache"],
      "cache-from": ["type=local,mode=max,src=/tmp/docker-cache"],
      "output": ["type=docker"]
    }
  }
}
```
