### ISSUE TITLE
attach mode is not working

### ISSUE THREAD

**Issue by mfmbarros** [hoverkraft-tech/compose-action#74]
**Description:** A clear and concise description of what the bug is.

Looks like detach mode is enabled by default as I'm not passing any flags and still, no output is observed after docker compose starts the container, which is somehow unexpected since detach mode is disabled by default when using docker-compose cli directly.
Nevertheless, I couldn't enable attach mode by passing either "--attach myContainer" or "--attach-dependencies" in up-flags, both ending on the following error:

```
Run hoverkraft-tech/compose-action@v2.0.0
2.23.0
docker-compose version: 2.23.0
--detach cannot be combined with --abort-on-container-exit, --attach or --attach-dependencies
Error: {"exitCode":1,"err":"--detach cannot be combined with --abort-on-container-exit, --attach or --attach-dependencies\n","out":""}
```

**Action version:** hoverkraft-tech/compose-action@v2.0.0

**Runner type:**

- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  

```
    - name: Run test container
      uses: hoverkraft-tech/compose-action@v2.0.0
      with:
        compose-file: ${{ inputs.docker-compose-file }}
        up-flags: "--attach-dependencies"
      env:
        TF_VAR_token: ${{ secrets.MY_TOKEN}}
```

**Expected behavior:** Expect to run container in attach mode

**Actual behavior:** When forcing attach mode, action errors with the message provided in description section.
