### ISSUE TITLE
compose-file input does not handle absolute path properly

### ISSUE THREAD

**Issue by neilime** [hoverkraft-tech/compose-action#81]
It appears that it may be checking for the `docker-compose.yml` file relative to the current working directory, so if you have specified an absolute path to the `compose-file`, then the check fails even though the file is in the right location for the build. Example from a run I tried:

Run hoverkraft-tech/compose-action@v2.0.1
```yml
  with:
    compose-file: /runner/_work/myrepo/myrepo/myaction/docker/docker-compose.yml
    cwd: /runner/_work/myrepo/myrepo
  env:
    GH_TOKEN: ***
    WORK_DIR: /runner/_work/myrepo/myrepo/myaction/build/work
    HOME: /runner/_work/myrepo/myrepo/myaction
    ... some other environment variables
```

Error: 

> Error: /runner/_work/myrepo/myrepo/myaction/docker/docker-compose.yml does not exist in /runner/_work/myrepo/myrepo

_Originally posted by @jayrifkinsv in https://github.com/hoverkraft-tech/compose-action/issues/21#issuecomment-2310804360_
